service: demoapi-blockdev-io
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  profile: personal
  memorySize: 128
  reservedConcurrency: 1
  timeout: 1
  apiGateway:
    shouldStartNameWithService: true

custom:
  customDomain:
    domainName: demoapi.blockdev.io
    basePath: ''
    createRoute53Record: false

plugins:
  - serverless-domain-manager

functions:
  api:
    handler: api.handler
    events:
      - http:
          path: 'v1/{path+}'
          method: any

